config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#index"

  namespace :admin do
    resources :users, :only => :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  paginates_per 50

  def make_admin
    update!(:admin => true)
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin!

    private

    def authenticate_admin!
      not_found unless current_user.admin?
    end

    def not_found
      raise ActionController::RoutingError, "Not Found"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = ::User.order(:created_at => :desc).page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :prepend => true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_page?
    request.path.start_with?("/admin")
  end
end

app/views/admin/users/index.html.erb
<h3>Users (<%= @users.count %>)</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Email</th>
      <th scope="col">Created At</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination-container">
  <%= paginate @users %>
</div>

app/views/layouts/_admin_navigation.html.erb
<% if current_user.admin? %>
  <%= link_to "Users", admin_users_path, :class => "nav-link" %>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container mb-5">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Hackberry Rails Starter", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if signed_in? %>
          <% if admin_page? %>
            <%= render "layouts/admin_navigation" %>
          <% else %>
            <%= render "layouts/user_navigation" %>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, :class => "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_user_navigation.html.erb
<li class="nav-item">
  <%= link_to "Account", edit_user_registration_path, :class => "nav-link" %>
</li>
<% if current_user.admin? %>
  <%= link_to "Admin", admin_users_path, :class => "nav-link" %>
<% end %>
<li class="nav-item">
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "nav-link" %>
</li>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>RailsStarter</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navigation" %>

    <div class="container">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hackberry Rails Starter App</h1>